### ISSUE TITLE
Not using GPU

### ISSUE THREAD

**Issue by deletedcookie** [seanghay/uvr-mdx-infer#2]
It is only using my CPU and not my GPU. Do I have to change anything to make it use my GPU?

I only have a 1050ti, which is below the minimum specs, but it works fine on the GUI version and is twice as fast as my CPU.

**Comment by seanghay** [comment]
It will use the GPU when possible. However, if it doesn't you might need to check your PyTorch dependencies to make sure it's the cuda version not cpu version. To install PyTorch CUDA, you may need to follow: https://pytorch.org/get-started/locally/

**Comment by deletedcookie** [comment]
Thanks, I thought I had the cuda version but it didn't for some reason. It works fine now after uninstalling and reinstalling with the cuda version.
